### ISSUE TITLE
settings in windows

### ISSUE THREAD

**Issue by linygany1** [incheon-kim/tarkov-settings#2]
was playing tarkov with this program, but my light(at home) suddenly turn off, after pc restart i have all this settings affecting windows without ever program opened, how to reset it ?

**Comment by incheon-kim** [comment]
You can re-calibrate color with dccw. It is provided with Windows itself.
Win + R >> "dccw"

**Comment by linygany1** [comment]
But there no is saturation settings
Ye, i done that, thanks, kinda not what i want bc it isnt reset, just new settings but ok!!

**Comment by incheon-kim** [comment]
You can find Saturation settings from Nvdia Control Panel as "Digital Vibrance"
I will consider putting a button set everything to zero.

Basically, this program gets LUT values when it is executed. And it reverts to the value when application is closing.
That's why your display color values get weird.
